### ISSUE TITLE
Add standard deviation

### ISSUE THREAD

**Issue by vnmabus** [GAA-UAM/scikit-fda#541]
Add a method for computing standard deviation of functional data both in discretized and basis expansions.

**Comment by pcuestas** [comment]
There is an issue regarding the design of the std function that should be specified, which is the normalization coefficient to be applied and whether it should be up to the user.

The definition of `std` provided in Kokoszka and Reimherr (2017) is:

$$(std_X(t) ) ^2=\frac{1}{N} \sum_{n=1}^{N} (X_n(t) - \bar{X}(t))^2.$$

This normalization by $N$ is the default used in [`numpy.var`](https://numpy.org/doc/stable/reference/generated/numpy.var.html) and [`numpy.std`](https://numpy.org/doc/stable/reference/generated/numpy.std.html), the latter being the most natural function to use when implementing `FDataGrid.std`:

```python
def std(X: FDataGrid) -> FDataGrid:
    return X.copy(
        data_matrix=np.array([np.std(X.data_matrix, axis=0)]),
        sample_names=("standard deviation",),
    )
```

However, the most natural way of defining the std of a FDataBasis object is to use the `FDataBasis.cov` method. `FDataBasis.cov` calculates the covariance using the formula:

$$(K_X(t, s) ) ^2=\frac{1}{N-1} \sum_{n=1}^{N} (X_n(t) - \bar{X}(t))(X_n(s) - \bar{X}(s)),$$

because $(N-1)$ is the default normalization used by [`numpy.cov`](https://numpy.org/doc/stable/reference/generated/numpy.cov.html).

A natural solution to this issue would be to make the signature of `std` similar to that of [`numpy.std`](https://numpy.org/doc/stable/reference/generated/numpy.std.html), where there is a parameter:
```
ddof: int, optional
    Means Delta Degrees of Freedom. The divisor used in calculations is N - ddof, where N represents the number of elements. By default ddof is zero.
```

**Comment by pcuestas** [comment]
I closed this issue by accident. Sorry.
