### ISSUE TITLE
Time x Space tutorial with basis representation and FPCA ?

### ISSUE THREAD

**Issue by mat-ej** [GAA-UAM/scikit-fda#568]
Hi Scikit-Fda team, 

First, let me start by saying that this is one of the best packages I have ever stumbled upon. Your tutorials are top notch introduction into functional data analysis. I love the way it is similar and works beautifully with original sci kit learn. 

What I am missing is a tutorial or perhaps just a short guide on how to work with Time x (Latitude, Longitude) data. I have found the tutorial for dealing with time and I have found tutorial for dealing with surfaces.

[https://fda.readthedocs.io/en/latest/auto_examples/plot_composition.html](https://fda.readthedocs.io/en/latest/auto_examples/plot_composition.html)

The tutorials are very good, but I am having trouble understanding how to construct basis representation for 
(Latitude x Longitude x Time) data, how can I perform FPCA in that case etc. 

Is there such a tutorial or perhaps a slack community where I might get some pointers? : ) 

Thanks in advance for your help and such an awesome package. 

Have a great week.

**Comment by vnmabus** [comment]
> First, let me start by saying that this is one of the best packages I have ever stumbled upon. Your tutorials are top notch introduction into functional data analysis. I love the way it is similar and works beautifully with original scikit learn.

Thank you! Making our work compatible with scikit-learn is one of our core principles, as it allows familiarity and code reuse, and simplifies some workflows in which both functional and multivariate data appear.

> What I am missing is a tutorial or perhaps just a short guide on how to work with Time x (Latitude, Longitude) data. I have found the tutorial for dealing with time and I have found tutorial for dealing with surfaces.
> 
> https://fda.readthedocs.io/en/latest/auto_examples/plot_composition.html

As functional data analysis is a large topic, we have focused first in the 1D (curves) case, in both the code and documentation. I agree that we should attempt to improve that situation. The state of the package (develop branch) in the ND case is the following:
- Functions of several variables discretized in a complete grid can be represented as a [`FDataGrid`](https://fda.readthedocs.io/en/latest/modules/autosummary/skfda.representation.grid.FDataGrid.html).
- Some bases, such as [`TensorBasis`](https://fda.readthedocs.io/en/latest/modules/autosummary/skfda.representation.basis.TensorBasis.html) and [`FiniteElementBasis`](https://fda.readthedocs.io/en/latest/modules/autosummary/skfda.representation.basis.FiniteElementBasis.html) can be employed to create a basis for functions of several variables.
- The conversion from `FDataGrid` to [`FDatabasis`](https://fda.readthedocs.io/en/latest/modules/autosummary/skfda.representation.basis.FDataBasis.html) should work (but may be slow or use much memory).
- Many of the methods that work with `FDataGrid` do not attempt to work with functions of several variables. A notable exception are methods based on distances, which will work if the distance is defined for such functions (e.g. the default L2 distance).
- As a design principle, we try to make the methods work in general if it is not too difficult. However, if it slows development too much we focus in the 1D case. Methods that do not support several variables should raise an exception when that type of data is provided (but as we do not focus for now in that case, it is probable that some failed to do so and produce bogus results instead. This should be treated as a bug).
- Methods that use `FDataBasis` tend to work also with basis for functions of several variables, as they are usually based on the inner product, which is implemented for that case. However, they MAY be slow or use much memory. An example of these methods would be FPCA for `FDataBasis`.
- Unfortunately, we have not yet implemented [`LinearDifferentialOperator`](https://fda.readthedocs.io/en/latest/modules/misc/autosummary/skfda.misc.operators.LinearDifferentialOperator.html) for the ND case, so smoothing based on the derivatives will not work.

> The tutorials are very good, but I am having trouble understanding how to construct basis representation for (Latitude x Longitude x Time) data, how can I perform FPCA in that case etc.

- If your data has been measured in a complete grid Latitude x Longitude x Time you can represent it as a `FDataGrid`.
- Then, you can create a [`TensorBasis`](https://fda.readthedocs.io/en/latest/modules/autosummary/skfda.representation.basis.TensorBasis.html) passing to it the individual desired 1D bases for the Latitude, Longitude and Time.
- You can convert your original discretized data to `FDataBasis` using either the `to_basis` method or the `BasisSmoother` class.
- You can then use the [`FPCA`](https://fda.readthedocs.io/en/latest/modules/preprocessing/autosummary/skfda.preprocessing.dim_reduction.FPCA.html) class to perform FPCA in basis form.

> Is there such a tutorial or perhaps a slack community where I might get some pointers? : )

As I said, we should improve the tutorial including topics such as registration, classification or regression, and probably also a section on functions of several variables.
We do not have a Slack (nor Discord nor Matrix) community. I agree that it would be an amazing resource to have, but we do not have currently the time to manage one. We have however the [Github discussions](https://github.com/GAA-UAM/scikit-fda/discussions) open, so that users of the package (or functional data analysis researchers/practitioners, even if they do not use it) can ask and answer questions or comment in related topics.

> Thanks in advance for your help and such an awesome package.

Thank you again! I hope that my answers helped you.

**Comment by mat-ej** [comment]
Thanks for answer, I ll move my question to the discussions
